s= set()
numbers= input("Enter Number : ")
s.add(int(numbers))
numbers= input("Enter Number : ")
s.add(int(numbers))
numbers= input("Enter Number : ")
s.add(int(numbers))
numbers= input("Enter Number : ")
s.add(int(numbers))
numbers= input("Enter Number : ")
s.add(int(numbers))
numbers= input("Enter Number : ")
s.add(int(numbers))
numbers= input("Enter Number : ")
s.add(int(numbers))
print(s)
s.add("18")
print(s)