dict={}
i=input("Enter the friend name : ")
n=input("Enter Language name : ")
dict.update({i:n})
i=input("Enter the friend name : ")
n=input("Enter Language name : ")
dict.update({i:n})
i=input("Enter the friend name : ")
n=input("Enter Language name : ")
dict.update({i:n})
i=input("Enter the friend name : ")
n=input("Enter Language name : ")
dict.update({i:n})
i=input("Enter the friend name : ")
n=input("Enter Language name : ")
dict.update({i:n})
print(dict)
