fruits=[]
s1=input("Enter fruit name : ")
fruits.append(s1)
s2=input("Enter fruit name : ")
fruits.append(s2)
s3=input("Enter fruit name : ")
fruits.append(s3)
s4=input("Enter fruit name : ")
fruits.append(s4)
s5=input("Enter fruit name : ")
fruits.append(s5)
s6=input("Enter fruit name : ")
fruits.append(s6)
print(fruits)