marks=[]
s1=input("Enter Student marks : ")
marks.append(s1)
s2=input("Enter Student marks : ")
marks.append(s2)
s3=input("Enter Student marks : ")
marks.append(s3)
s4=input("Enter Student marks : ")
marks.append(s4)
s5=input("Enter Student marks : ")
marks.append(s5)
s6=input("Enter Student marks : ")
marks.append(s6)
s7=input("Enter Student marks : ")
marks.append(s7)
print(marks)